### ISSUE TITLE
It uses fontawesome-pro but where is the token?

### ISSUE THREAD

**Issue by danirus** [Infineon/Infineon-Design-System-Bootstrap#1]
**Prerequisites**

Can you reproduce the problem reliably? 
Yes

Did you check current release notes for known issues?
-Yes

If this is not the latest release, have you checked newer releases? 
-I am using the latest.

**Description**:

Running `npm install --save @infineon/design-system-bootstrap` fails. The README.md doesn't mention that the package requires the `fontawesome-pro` package, and doesn't include instructions on how to get the token.

**Steps to Reproduce:**

1. On a computer without the required fontawesome token, the install command fails. 

**Expected Result:**

That it installs without issues.

**Actual Result:**

It fails to install.

**Frequency (1/1, 1/50, 1/100):**

1/1.

**Build/Commit:**

Please specify the release, like 1.4.1. If there is no release, give us the commit for the code you used.
1.0.1

**Target:**

An HP Elitebook laptop provided by Infineon.

**Host OS and Version:**

Windows

**Compiler:**

This package doesn't require any compiler to be installed. I guess you have copy-pasted all this questions from somewhere else.

**Environment**

Just want to use the package. The environment is veeery nice. This region is full of lakes and forest.

**Comment by kaiwerther** [comment]
Please get in Contact with dds@infineon.com to get your token. We updated the read.me accordingly.
Thank you for your ticket!
